# Webhook test
# HTTP 代理端口
port: 1087
# SOCKS5 代理端口
socks-port: 1080
# Linux 和 macOS 的 redir 透明代理端口 (重定向 TCP 和 TProxy UDP 流量)
# redir-port: 7892

# Linux 的透明代理端口（适用于 TProxy TCP 和 TProxy UDP 流量)
# tproxy-port: 7893

# HTTP(S) and SOCKS5 共用端口
# mixed-port: 7890

# 本地 SOCKS5/HTTP(S) 服务验证
# authentication:
#  - "user1:pass1"
#  - "user2:pass2"

# 允许局域网的连接（可用来共享代理）
allow-lan: true
bind-address: "*"
# 此功能仅在 allow-lan 设置为 true 时生效，支持三种参数：
# "*"                           绑定所有的 IP 地址
# 192.168.122.11                绑定一个的 IPv4 地址
# "[aaaa::a8aa:ff:fe09:57d8]"   绑定一个 IPv6 地址

# Clash 路由工作模式
# 规则模式：rule（规则） / global（全局代理）/ direct（全局直连）
mode: rule
# Clash 默认将日志输出至 STDOUT
# 设置日志输出级别 (默认级别：silent，即不输出任何内容，以避免因日志内容过大而导致程序内存溢出）。
# 5 个级别：silent / info / warning / error / debug。级别越高日志输出量越大，越倾向于调试，若需要请自行开启。
log-level: silent
# clash 的 RESTful API 监听地址
external-controller: 127.0.0.1:9090
# 存放配置文件的相对路径，或存放网页静态资源的绝对路径
# Clash core 将会将其部署在 http://{{external-controller}}/ui
# external-ui: folder

# RESTful API 的口令 (可选)
# 通过 HTTP 头中 Authorization: Bearer ${secret} 参数来验证口令
# 当 RESTful API 的监听地址为 0.0.0.0 时，请务必设定口令以保证安全
# secret: ""

# 出站网卡接口
# interface-name: en0

# DNS 服务器和建立连接时的 静态 Hosts, 仅在 dns.enhanced-mode 模式为 redir-host 生效
# 支持通配符域名 (例如: *.clash.dev, *.foo.*.example.com )
# 不使用通配符的域名优先级高于使用通配符的域名 (例如: foo.example.com > *.example.com > .example.com )
# 注意: +.foo.com 的效果等同于 .foo.com 和 foo.com
hosts:
# '*.clash.dev': 127.0.0.1
# '.dev': 127.0.0.1
# 'alpha.clash.dev': '::1'

# DNS 服务器配置(可选；若不配置，程序内置的 DNS 服务会被关闭)
dns:
  enable: true
  enhanced-mode: fake-ip # 或 redir-host
  # use-hosts: true # 查询 hosts 并返回 IP 记录
  # 支持 UDP / TCP / DoT / DoH 协议的 DNS 服务，可以指明具体的连接端口号。
  # 所有 DNS 请求将会直接发送到服务器，不经过任何代理。
  # Clash 会使用最先获得的解析记录回复 DNS 请求
  nameserver:
  - https://dns.alidns.com/dns-query
  fallback:
  - https://1.1.1.1/dns-query
  - https://dns.google/dns-query
  # 当 fallback 参数被配置时, DNS 请求将同时发送至上方 nameserver 列表和下方 fallback 列表中配置的所有 DNS 服务器.
  # 当解析得到的 IP 地址的地理位置不是 CN 时，clash 将会选用 fallback 中 DNS 服务器的解析结果。
  # fallback:
  #   - https://dns.google/dns-query

  # 如果使用 nameserver 列表中的服务器解析的 IP 地址在下方列表中的子网中，则它们被认为是无效的，
  # Clash 会选用 fallback 列表中配置 DNS 服务器解析得到的结果。
  #
  # 当 fallback-filter.geoip 为 true 且 IP 地址的地理位置为 CN 时，
  # Clash 会选用 nameserver 列表中配置 DNS 服务器解析得到的结果。
  #
  # 当 fallback-filter.geoip 为 false, 如果解析结果不在 fallback-filter.ipcidr 范围内，
  # Clash 总会选用 nameserver 列表中配置 DNS 服务器解析得到的结果。
  #
  # 采取以上逻辑进行域名解析是为了对抗 DNS 投毒攻击。
  fallback-filter:
    geoip: false
    ipcidr:
      - 240.0.0.0/4
      - 0.0.0.0/32
      # domain:
      #   - '+.google.com'
      #   - '+.facebook.com'
      #   - '+.youtube.com'
proxies:
  - name: azure-sg-hysteria                           
    type: hysteria2                                      
    server: wenhelog.com                               
    port: 36897                                
    auth: 429db6aa-6eb8-4433-a0a6-21c28d0393c7                                                      
    skip-cert-verify: false
    fast-open: true
  - name: azure-hk-trojan
    type: trojan
    server: wenhe.one
    port: 443
    password: 70213703-9946-4330-b8bc-7c32ad590cc8
    skip-cert-verify: true
    udp: true
    alpn:
      - http/1.1
  - name: azure-us-trojan
    type: trojan
    server: buwenhe.com
    port: 443
    password: 21a7a119-5e89-487b-b813-bf15152b3d19
    skip-cert-verify: true
    udp: true
    alpn:
      - http/1.1
  - name: azure-sg-tuic
    server: hermanwen.xyz
    port: 51296
    type: tuic
    version: 5
    uuid: 7c6695a0-f18e-4afb-ba78-4f7c90a54206
    password: 7c6695a0-f18e-4afb-ba78-4f7c90a54206
    sni: hermanwen.xyz
    skip-cert-verify: false
    alpn:
      - h3

proxy-groups:
  # 代理的转发链, 在 proxies 中不应该包含 relay. 不支持 UDP.
  # 流量: clash <-> http <-> vmess <-> ss1 <-> ss2 <-> 互联网
  # - name: "relay"
  #   type: relay
  #   proxies:
  #     - http
  #     - vmess
  #     - ss1
  #     - ss2
  - name: APPLE
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Apple.png
    proxies:
      - PROXY
      - DIRECT
  - name: CRYPTO
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Want_Want_Letter.png
    proxies:
      - azure-sg-tuic
      - azure-sg-hysteria
      - azure-hk-trojan
      - azure-us-trojan
      - TAG-select
      - DIRECT
  # url-test 可以自动选择与指定 URL 测速后，延迟最短的服务器
  - name: Fastest
    type: url-test
    proxies:
      - azure-sg-tuic
      - azure-sg-hysteria
      - azure-hk-trojan
      - azure-us-trojan
    url: "http://www.gstatic.com/generate_204"
    interval: 300
  # fallback 可以尽量按照用户书写的服务器顺序，在确保服务器可用的情况下，自动选择服务器
  - name: Fallback
    type: fallback
    proxies:
      - azure-sg-tuic
      - azure-sg-hysteria
      - azure-hk-trojan
      - azure-us-trojan
    url: "http://www.gstatic.com/generate_204"
    interval: 300
  # # load-balance 可以使相同 eTLD 请求在同一条代理线路上
  # - name: "load-balance"
  #   type: load-balance
  #   proxies:
  #     - ss1
  #     - ss2
  #     - vmess1
  #   url: 'http://www.gstatic.com/generate_204'
  #   interval: 300
  - name: AI_SERVICE
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Server.png
    proxies:
      - PROXY
      - azure-sg-tuic
      - azure-sg-hysteria
      - azure-hk-trojan
      - azure-us-trojan
      - TAG-select
      - DIRECT
  # select 用来允许用户手动选择 代理服务器 或 服务器组
  # 您也可以使用 RESTful API 去切换服务器，这种方式推荐在 GUI 中使用
  - name: PROXY
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Proxy.png
    proxies:
      - Fallback
      - azure-sg-tuic
      - azure-sg-hysteria
      - azure-hk-trojan
      - azure-us-trojan
      - TAG-select
  - name: TAG-select
    type: select
    use:
      - TAG
proxy-providers:
  TAG:
    url: https://chomthong.central-world.org/api/v1/client/subscribe?token=ff9d01f639de98c709269af5b6b11713
    interval: 3600
    filter: '家宽'
# test:
#   type: file
#   path: /test.yaml
#   health-check:
#     enable: true
#     interval: 36000
#     url: http://www.gstatic.com/generate_204
rule-providers:
  reject:
    behavior: domain
    format: yaml
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt"
    path: ./ruleset/reject.yaml
    interval: 86400
  icloud:
    behavior: domain
    format: yaml
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.txt"
    path: ./ruleset/icloud.yaml
    interval: 86400
  apple:
    behavior: domain
    format: yaml
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt"
    path: ./ruleset/apple.yaml
    interval: 86400
  google:
    behavior: domain
    format: yaml
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/google.txt"
    path: ./ruleset/google.yaml
    interval: 86400
  proxy:
    behavior: domain
    format: yaml
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt"
    path: ./ruleset/proxy.yaml
    interval: 86400
  direct:
    behavior: domain
    format: yaml
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt"
    path: ./ruleset/direct.yaml
    interval: 86400
  gfw:
    behavior: domain
    format: yaml
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt"
    path: ./ruleset/gfw.yaml
    interval: 86400
  greatfire:
    behavior: domain
    format: yaml
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/greatfire.txt"
    path: ./ruleset/greatfire.yaml
    interval: 86400
  tld-not-cn:
    behavior: domain
    format: yaml
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/tld-not-cn.txt"
    path: ./ruleset/tld-not-cn.yaml
    interval: 86400
  telegramcidr:
    behavior: ipcidr
    format: yaml
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt"
    path: ./ruleset/telegramcidr.yaml
    interval: 86400
  cncidr:
    behavior: ipcidr
    format: yaml
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt"
    path: ./ruleset/cncidr.yaml
    interval: 86400
  lancidr:
    behavior: ipcidr
    format: yaml
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt"
    path: ./ruleset/lancidr.yaml
    interval: 86400
  openai:
    type: http
    behavior: domain
    format: text
    url: "http://script.hub/file/_start_/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/OpenAI/OpenAI.list/_end_/OpenAI.list?type=rule-set&target=stash-domain-set&del=true"
    path: ./ruleset/openai.yaml
    interval: 86400
  gemini:
    type: http
    behavior: domain
    format: text
    url: "http://script.hub/file/_start_/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Surge/Gemini/Gemini.list/_end_/Gemini.list?type=rule-set&target=stash-domain-set&del=true"
    path: ./ruleset/gemini.yaml
    interval: 86400
rules:
  - PROCESS-NAME,v2ray,DIRECT
  - PROCESS-NAME,xray,DIRECT
  - PROCESS-NAME,clash,DIRECT
  - PROCESS-NAME,naive,DIRECT
  - PROCESS-NAME,trojan,DIRECT
  - PROCESS-NAME,trojan-go,DIRECT
  - PROCESS-NAME,ss-local,DIRECT
  - PROCESS-NAME,privoxy,DIRECT
  - PROCESS-NAME,leaf,DIRECT
  - PROCESS-NAME,Thunder,DIRECT
  - PROCESS-NAME,DownloadService,DIRECT
  - PROCESS-NAME,qBittorrent,DIRECT
  - PROCESS-NAME,Transmission,DIRECT
  - PROCESS-NAME,fdm,DIRECT
  - PROCESS-NAME,aria2c,DIRECT
  - PROCESS-NAME,Folx,DIRECT
  - PROCESS-NAME,NetTransport,DIRECT
  - PROCESS-NAME,uTorrent,DIRECT
  - PROCESS-NAME,WebTorrent,DIRECT
  - DOMAIN,clash.razord.top,DIRECT
  - DOMAIN,yacd.haishan.me,DIRECT
  - IP-CIDR,192.168.0.0/8,DIRECT
  - DOMAIN-KEYWORD,deribit,PROXY
  - DOMAIN-KEYWORD,newrelic,PROXY
  - DOMAIN,manhuafen.com,PROXY
  - DOMAIN-KEYWORD,perplexity,AI_SERVICE
  - DOMAIN-KEYWORD,pplx,AI_SERVICE
  - DOMAIN-KEYWORD,binance,CRYPTO
  - DOMAIN-KEYWORD,bnappzh,CRYPTO
  - DOMAIN-KEYWORD,bntrace,CRYPTO
  - RULE-SET,reject,REJECT
  - RULE-SET,openai,AI_SERVICE
  - RULE-SET,gemini,AI_SERVICE
  - RULE-SET,icloud,APPLE
  - RULE-SET,apple,APPLE
  - RULE-SET,google,PROXY
  - RULE-SET,proxy,PROXY
  - RULE-SET,direct,DIRECT
  - RULE-SET,lancidr,DIRECT
  - RULE-SET,cncidr,DIRECT
  - RULE-SET,telegramcidr,PROXY
  - GEOIP,LAN,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,PROXY
